### ISSUE TITLE
Typo Finable -> Findable

### ISSUE THREAD

**Issue by neurolabusc** [ReproNim/module-FAIR-data#12]
[Finable](https://www.merriam-webster.com/dictionary/finable) should be `Findable` in the [Data and the FAIR Principles](https://github.com/ReproNim/module-FAIR-data/blob/a1b607b5e465cecec7b4017502fdd950fa00edc4/_episodes/00-Introduction-to-Module.md) introduction.

**Comment by jgrethe** [comment]
Thanks - should be fixed now in gh-pages
